spring.application.name=bienestar
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.main.allow-bean-definition-overriding=true

# Database Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_bienestar?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Run data.sql after Hibernate creates the schema
spring.jpa.defer-datasource-initialization=true
# Always run the initialization scripts
spring.sql.init.mode=always
# Specify the order of execution for SQL scripts
spring.sql.init.data-locations=classpath:departamentos.sql,classpath:provincias.sql,classpath:distritos.sql