package pe.edu.unitru.bienestar.staff.domain;

public enum MedicalSpeciality {
    GENERAL_PRACTICE,
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GYNECOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIOLOGY,
    TRAUMATOLOGY,
    UROLOGY
}
